CREATE TABLE IF NOT EXISTS `property_billing_records` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `property_list_id` INT NOT NULL,
    `dd` VARCHAR(120) NOT NULL,
    `property` VARCHAR(160) NOT NULL,
    `due_period` VARCHAR(7) NOT NULL DEFAULT '',
    `unit_owner` VARCHAR(180) NOT NULL,
    `bill_type` VARCHAR(32) NOT NULL DEFAULT 'water',
    `is_hidden` TINYINT(1) NOT NULL DEFAULT 0,
    `classification` VARCHAR(120) DEFAULT '',
    `deposit` VARCHAR(80) DEFAULT '',
    `rent` VARCHAR(80) DEFAULT '',
    `internet_provider` VARCHAR(140) DEFAULT '',
    `internet_account_no` VARCHAR(120) DEFAULT '',
    `wifi_amount` VARCHAR(80) DEFAULT '',
    `wifi_due_date` VARCHAR(80) DEFAULT '',
    `wifi_payment_status` VARCHAR(100) DEFAULT '',
    `water_account_no` VARCHAR(120) DEFAULT '',
    `water_amount` VARCHAR(80) DEFAULT '',
    `water_due_date` VARCHAR(80) DEFAULT '',
    `water_payment_status` VARCHAR(100) DEFAULT '',
    `electricity_account_no` VARCHAR(120) DEFAULT '',
    `electricity_amount` VARCHAR(80) DEFAULT '',
    `electricity_due_date` VARCHAR(80) DEFAULT '',
    `electricity_payment_status` VARCHAR(100) DEFAULT '',
    `association_dues` VARCHAR(80) DEFAULT '',
    `association_due_date` VARCHAR(80) DEFAULT '',
    `association_payment_status` VARCHAR(100) DEFAULT '',
    `real_property_tax` VARCHAR(80) DEFAULT '',
    `rpt_payment_status` VARCHAR(100) DEFAULT '',
    `penalty` VARCHAR(80) DEFAULT '',
    `per_property_status` VARCHAR(100) DEFAULT '',
    `active_property_list_id` INT GENERATED ALWAYS AS (CASE WHEN `is_hidden` = 0 THEN `property_list_id` ELSE NULL END) STORED,
    `active_due_period` VARCHAR(7) GENERATED ALWAYS AS (CASE WHEN `is_hidden` = 0 THEN `due_period` ELSE NULL END) STORED,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KEY `idx_property_billing_property_list_id` (`property_list_id`),
    KEY `idx_pbr_hidden_due_period_created` (`is_hidden`, `due_period`, `created_at`, `id`),
    UNIQUE KEY `uq_pbr_active_property_due_period` (`active_property_list_id`, `active_due_period`)
);
